/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LiteYoutube {
    'addPrefetch': (kind: any, url: any, as?: string) => Promise<void>;
    'dataVideoid': string;
  }
}

declare global {


  interface HTMLLiteYoutubeElement extends Components.LiteYoutube, HTMLStencilElement {}
  var HTMLLiteYoutubeElement: {
    prototype: HTMLLiteYoutubeElement;
    new (): HTMLLiteYoutubeElement;
  };
  interface HTMLElementTagNameMap {
    'lite-youtube': HTMLLiteYoutubeElement;
  }
}

declare namespace LocalJSX {
  interface LiteYoutube {
    'dataVideoid'?: string;
  }

  interface IntrinsicElements {
    'lite-youtube': LiteYoutube;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lite-youtube': LocalJSX.LiteYoutube & JSXBase.HTMLAttributes<HTMLLiteYoutubeElement>;
    }
  }
}


